import { NextResponse } from 'next/server';
import { chunkPages } from '@/lib/chunker';
import { documentFromPlainText, extractTextFromPDF, type ExtractedDocument } from '@/lib/pdf-extract';
import { extractTextFromPPTX } from '@/lib/pptx-extract';
import { parseYouTubeUrl } from '@/lib/notes-types';
import { createMaterial, saveChunks, saveVideoNotes } from '@/lib/store';
import { DEMO_USER_ID, handleRouteError, jsonError } from '@/lib/api-utils';

/** pdf.js needs Node APIs; it cannot run on the edge runtime. */
export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';

const MAX_FILE_BYTES = 20 * 1024 * 1024;
const MIN_USABLE_CHARS = 200;

/**
 * POST /api/upload — accepts a PDF (multipart) or pasted text (JSON), extracts
 * the text, stores the material, and writes page-aware chunks ready for
 * embedding (PRD §5.1).
 *
 * Embeddings are generated by /api/generate-embeddings so the student sees
 * learning cards without waiting on the full vector pass.
 */
export async function POST(request: Request) {
  try {
    const contentType = request.headers.get('content-type') ?? '';
    let document: ExtractedDocument;
    let title: string;
    let userId = DEMO_USER_ID;

    if (contentType.includes('application/json')) {
      const body = await request.json();
      userId = body.user_id || DEMO_USER_ID;

      // Video → Notes. A YouTube URL needs no upload at all: Gemini accepts the
      // watch URL directly, which sidesteps Vercel's 4.5 MB request body cap.
      if (typeof body.youtube_url === 'string' && body.youtube_url.trim()) {
        const watchUrl = parseYouTubeUrl(body.youtube_url);
        if (!watchUrl) {
          return jsonError('That does not look like a YouTube link. Paste a youtube.com or youtu.be URL.');
        }

        const material = await createMaterial(userId, body.title?.trim() || 'YouTube lecture', '', {
          sourceUnit: 'timestamp',
          contentType: 'video',
          videoUrl: watchUrl,
          videoDurationSeconds: toDuration(body.duration_seconds),
        });

        await saveVideoNotes({
          material_id: material.id,
          notes_json: null,
          status: 'pending',
          progress_message: null,
          error: null,
          segment_index: 0,
          segment_total: 1,
          gemini_file_uri: null,
        });

        return NextResponse.json({
          material_id: material.id,
          title: material.title,
          content_type: 'video',
          video_url: watchUrl,
        });
      }

      // A video already uploaded straight to Storage by the browser.
      if (typeof body.storage_path === 'string' && body.storage_path.trim()) {
        const material = await createMaterial(userId, body.title?.trim() || 'Uploaded lecture', '', {
          sourceUnit: 'timestamp',
          contentType: 'video',
          videoUrl: body.storage_path.trim(),
          videoDurationSeconds: toDuration(body.duration_seconds),
        });

        await saveVideoNotes({
          material_id: material.id,
          notes_json: null,
          status: 'pending',
          progress_message: null,
          error: null,
          segment_index: 0,
          segment_total: 1,
          gemini_file_uri: null,
        });

        return NextResponse.json({
          material_id: material.id,
          title: material.title,
          content_type: 'video',
          video_url: material.video_url,
          storage_path: material.video_url,
        });
      }

      const text = typeof body.text === 'string' ? body.text : '';
      title = body.title || 'Pasted notes';

      if (text.trim().length < MIN_USABLE_CHARS) {
        return jsonError(`Paste at least ${MIN_USABLE_CHARS} characters so there is enough to work with.`);
      }
      document = documentFromPlainText(text);
    } else {
      const formData = await request.formData();
      const file = formData.get('file');
      userId = (formData.get('user_id') as string) || DEMO_USER_ID;

      if (!(file instanceof File)) return jsonError('No file provided.');
      if (file.size > MAX_FILE_BYTES) return jsonError('That file is larger than 20MB.');

      const name = file.name.toLowerCase();
      const isPdf = name.endsWith('.pdf');
      const isPptx = name.endsWith('.pptx');

      if (!isPdf && !isPptx) {
        return jsonError('Only PDF and PPTX files are supported. You can also paste your notes as text.');
      }

      title = file.name.replace(/\.(pdf|pptx)$/i, '');
      const buffer = Buffer.from(await file.arrayBuffer());
      document = isPptx ? await extractTextFromPPTX(buffer) : await extractTextFromPDF(buffer);
    }

    if (document.text.trim().length < MIN_USABLE_CHARS) {
      return jsonError(
        document.unit === 'slide'
          ? 'Could not read enough text from that deck. Slides made of images rather than text boxes cannot be read — try pasting the notes instead.'
          : 'Could not read enough text from that PDF. It may be scanned images rather than selectable text — try a text-based PDF or paste the notes instead.',
        422,
      );
    }

    const material = await createMaterial(userId, title, document.text, {
      sourceUnit: document.unit,
      contentType: 'document',
    });
    const chunks = chunkPages(document.pages);

    await saveChunks(
      material.id,
      chunks.map((chunk) => ({
        chunk_index: chunk.chunk_index,
        chunk_text: chunk.chunk_text,
        page_start: chunk.page_start,
        page_end: chunk.page_end,
        embedding: null,
      })),
    );

    return NextResponse.json({
      material_id: material.id,
      title: material.title,
      content_type: 'document',
      page_count: document.page_count,
      unit: document.unit,
      chunk_count: chunks.length,
      character_count: document.text.length,
    });
  } catch (error) {
    return handleRouteError('Upload', error);
  }
}

/** The browser reports duration from the <video>/player; treat junk as unknown. */
function toDuration(value: unknown): number | null {
  const seconds = Number(value);
  return Number.isFinite(seconds) && seconds > 0 ? Math.round(seconds) : null;
}
